version: "3.3"

services:
    web:
        image: nginx:latest
        ports:
            - "9010:80"
        volumes:
            - ./src-nginx:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm
        network_mode: bridge

    php-fpm:
        image: php:8.2.11RC1-fpm-bullseye
        ports:
            - "9000:9000"
        volumes:
            - ./src-fpm:/var/www/html
            - ./www.conf:/usr/local/etc/php-fpm.d/www.conf
        network_mode: bridge
        command: ["php-fpm", "-R"] # 添加要执行的命令

